#!/bin/sh
if test $(id -u) -ne 0; then
	echo "You must be root to run this script."
	exit 1
fi
spool="/var/spool/msg/$1"
if touch "$spool" && chown $1:msg "$spool" && chmod 660 "$spool"; then
	echo "Registered $1."
	exit 0
else
	echo "Registering $1 failed."
	exit 1
fi
