#!/bin/sh
if test $(id -u) -ne 0; then
	echo "You must be root to run this script."
	exit 1
fi
spool="/var/spool/msg/$1"
if test -a "$spool"; then
	if rm "$spool"; then
		echo "Unregisted $1."
		exit 0
	else
		echo "Failed to unregister $1."
		exit 1
	fi
else
	echo "$1 is not registered."
	exit 1
fi
